package com.oratakashi.design.docs.theme

import androidx.compose.ui.graphics.Color
import com.oratakashi.design.foundation.color.OrataDesignColorScheme
import kotlin.random.Random

data class MyColor(
    override val background: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val error: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val errorContainer: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val info: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val infoContainer: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val inverseOnSurface: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val inversePrimary: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val inverseSurface: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val onBackground: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val onError: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val onErrorContainer: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val onInfo: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val onInfoContainer: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val onPrimary: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val onPrimaryContainer: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val onSecondary: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val onSecondaryContainer: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val onSuccess: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val onSuccessContainer: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val onSurface: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val onSurfaceVariant: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val onTertiary: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val onTertiaryContainer: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val onWarning: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val onWarningContainer: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val outline: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val outlineVariant: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val primary: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val primaryContainer: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val scrim: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val secondary: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val secondaryContainer: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val success: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val successContainer: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val surface: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val surfaceBright: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val surfaceContainer: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val surfaceContainerHigh: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val surfaceContainerHighest: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val surfaceContainerLow: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val surfaceContainerLowest: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val surfaceDim: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val surfaceVariant: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val tertiary: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val tertiaryContainer: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val warning: Color = Color(Random.nextInt(0xFFFFFFFF.toInt())),
    override val warningContainer: Color = Color(Random.nextInt(0xFFFFFFFF.toInt()))
): OrataDesignColorScheme
